export const todoConst = {
  ADD_REQUEST: "ADD_REQUEST",
  ADD_SUCCESS: "ADD_SUCCESS",
  ADD_FAILURE: "ADD_FAILURE",

  GET_REQUEST: "GET_REQUEST",
  GET_SUCCESS: "GET_SUCCESS",
  GET_FAILURE: "GET_FAILURE",

  DELETE_REQUEST: "DELETE_REQUEST",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAILURE: "DELETE_FAILURE",

  UPDATE_REQUEST: "UPDATE_REQUEST",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILURE: "UPDATE_FAILURE",

  COMPLETED: "TASK_COMPLETED",
  UNCOMPLETED: "TASK_NOT_CONPLETED",
};
