export const todoConst = {
  ADD_TASK: "ADD_TASK",
  ADD_SUCCESS: "ADD_SUCCESS",
  ADD_FAILURE: "ADD_FAILURE",

  // UPDATE_TASK: "UPDATE_TASK",
  // UPDATE_SUCCESS: "UPDATE_SUCCESS",
  // UPDATE_FAILURE: "UPDATE_FAILURE",

  DRAFT: "DRAFT",
  DRAFT_SUCCESS: "DRAFT_SUCCESS",
  DRAFT_FAILURE: "DRAFT_FAILURE",

  READY: "READY",
  READY_SUCCESS: "READY_SUCCESS",
  READY_FAILURE: "READY_FAILURE",

  SUBMMITING: "SUBMMTTING",
  SUBMIT_SUCCESS: "SUCCESS",
  SUBMIT_ERROR: "ERROR",

  ONLINE: "ONLINE",
  OFFLINE: "OFFLINE",
  NETWORK: "NETWORK",

  REMOVE_ALL: "REMOVE_ALL",
};
